#!/usr/bin/env bash
# Single source of truth for the backlog. Sourced by the other scripts.
#
# Format:  ID | Title | Labels | Points | Story | AC1 ;; AC2 ;; AC3
# Keep this in sync with docs/user-stories.md.

STORIES=(
"US-01|Create an account|epic:accounts,must-have,backend,frontend|3|As a developer running side projects, I want to sign up with an email and password so that my monitors are private to me.|A valid email and an 8+ character password creates the account and signs me in ;; A duplicate email returns 409 with 'That email already has an account.' ;; Passwords are stored as salted PBKDF2-SHA256 hashes"
"US-02|Sign in|epic:accounts,must-have,backend,frontend|3|As a returning user, I want to sign in so that I can reach my dashboard.|Correct credentials return a JWT valid for 24 hours ;; Wrong credentials return 401 without revealing whether the email exists ;; The token is sent as a Bearer header on every API call"
"US-03|Stay signed in, and sign out on demand|epic:accounts,must-have,frontend|2|As a user, I want my session to survive a refresh and a sign-out button that ends it so that I am not retyping my password all day.|A page refresh keeps me signed in until the token expires ;; Sign out clears the token and redirects to /login ;; An expired or tampered token redirects to /login rather than showing a blank screen"
"US-04|Never see another account's data|epic:accounts,must-have,backend,security|3|As a user, I want hard isolation between accounts so that self-hosting for a small team is safe.|Every monitor and incident query filters by owner_id ;; Requesting a monitor I do not own returns 404, not 403 ;; A request with no Authorization header returns 401"
"US-05|See everything I watch on one screen|epic:monitors,must-have,frontend|5|As a developer, I want a single dashboard listing every monitor so that I know whether anything is broken in under five seconds.|Each row shows name, URL, status, 24h uptime, average response time, and last-checked time ;; Status is conveyed by label as well as colour ;; Zero monitors shows an empty state with a path to add one"
"US-06|Add a monitor in under ten seconds|epic:monitors,must-have,backend,frontend|3|As a developer, I want to add a URL with just a name so that setup is not a chore.|Only name and URL are required; method, expected status, and interval have defaults ;; The monitor appears immediately with status pending ;; The worker picks it up next cycle without a restart"
"US-07|Configure how a check is made|epic:monitors,must-have,backend|3|As a backend developer, I want to set method, expected status, and interval so that I can monitor API health endpoints, not just web pages.|Method, expected status, and interval are editable on create and edit ;; Interval is clamped server-side to 30-3600s with a readable 422 ;; A response status differing from expected counts as a failure"
"US-08|Judge health from the list, not the detail page|epic:monitors,must-have,backend|3|As a user, I want uptime and average response time on each row so that I can spot a service that is up but getting slower.|Uptime is successful checks over total checks in the trailing 24h, to two decimals ;; Average latency uses successful checks only ;; A monitor with no checks shows an em dash, not 0%"
"US-09|Watch the dashboard update itself|epic:monitors,should-have,frontend|2|As a user with the dashboard on a second screen, I want it to refresh itself so that it works as an ambient status display.|The dashboard re-fetches every 15 seconds ;; The poll is cancelled on unmount so timers do not leak ;; A failed poll shows an inline error and keeps retrying"
"US-10|Read the response-time history of one service|epic:monitors,must-have,frontend|5|As a developer investigating slowness, I want a 24-hour response-time chart so that I can tell a spike from a trend.|The chart plots every successful check in the window, oldest to newest ;; Failed checks are drawn as vertical markers so gaps are explained ;; Fewer than two samples shows 'Not enough samples yet'"
"US-11|Read the raw check log|epic:monitors,must-have,frontend|2|As a developer, I want the last ten checks with status code, latency, and error so that I can see exactly what the server returned.|Each row shows relative time, status or error, and latency ;; Errors are phrased for humans, not as exception class names ;; Successes and failures are visually distinguishable"
"US-12|Pause or remove a monitor|epic:monitors,must-have,backend,frontend|3|As a user decommissioning a service, I want to pause or delete a monitor so that a retired service stops paging me.|Pausing sets is_active false and the worker skips it ;; Deleting cascades to checks and incidents ;; Deletion asks for confirmation first"
"US-13|Have outages detected without me watching|epic:engine,must-have,backend|8|As a developer asleep at 3am, I want the system to notice failures on its own so that monitoring is not something I have to remember.|A dedicated worker container probes every active monitor whose interval has elapsed ;; Two consecutive failures flip the monitor to down and open an incident ;; A single failed check does not open an incident"
"US-14|Have recoveries detected too|epic:engine,must-have,backend|5|As a user, I want incidents to close themselves so that the incident list reflects reality without manual filing.|The first success after a failure resolves the open incident ;; The incident gets a plain-English summary with cause, duration, and current latency ;; The failure counter resets on success"
"US-15|See the incident history|epic:engine,must-have,backend,frontend|3|As a team lead, I want a reverse-chronological incident feed so that I can answer 'how often does this break?'|The feed shows monitor, cause, start time, duration, and state ;; I can filter to open incidents only ;; Results are capped at 100 per request"
"US-16|Publish a status page my users can read|epic:status,should-have,backend,frontend|5|As a solo founder, I want a public page showing which services are healthy so that customers stop emailing me during an outage.|/status/<handle> is readable with no authentication ;; An overall banner is derived from the worst individual status ;; Monitor URLs and internal errors are never exposed"
"US-17|Choose what is public|epic:status,should-have,backend,frontend|3|As a user, I want a per-monitor visibility toggle so that internal services stay internal.|Monitors default to private ;; Toggling updates the public page within one cache TTL ;; A page with no public monitors renders an empty state, not an error"
"US-18|Acknowledge an incident|epic:status,should-have,backend,frontend|2|As an on-call developer, I want to acknowledge an incident so that teammates know someone is on it.|Acknowledging is one click from the incident feed ;; The state persists and is visible to everyone on the account ;; Acknowledging does not resolve the incident"
"US-19|Get an email when something breaks|epic:alerting,should-have,backend|5|As a developer, I want an email when an incident opens so that I do not need the dashboard open to find out.|Email is sent on incident open and close, never per failed check ;; SMTP config comes from env vars and the feature disables cleanly when unset ;; A failed send retries twice then logs, never crashing the worker"
"US-20|Get alerts in Slack|epic:alerting,could-have,backend|3|As a small team, we want incidents posted to Slack so that alerts land where we already talk.|A webhook URL is configurable per account ;; The message names the service, the cause, and links to the monitor ;; Slack being down does not affect probing"
"US-21|Read a plain-English explanation of an outage|epic:alerting,could-have,backend|3|As a non-technical founder, I want the incident described in a sentence I understand so that I can decide whether to tell customers.|Every resolved incident carries a summary with service, duration, trigger, and current latency ;; The summary is generated at resolution and stored ;; No jargon in user-facing error text"
"US-22|Quiet hours|epic:alerting,wont-have,backend|5|As a developer who needs sleep, I want to suppress non-critical alerts overnight so that a flaky staging box does not wake me.|A per-account quiet window with timezone is configurable ;; Suppressed alerts still record incidents and appear in a morning digest ;; Monitors flagged critical bypass quiet hours"
"US-23|Run the whole stack with one command|epic:ops,must-have,devops|5|As a new contributor, I want docker compose up to give me a working system so that I am productive on day one.|One command starts db, cache, api, worker, and web with no manual steps ;; The API waits for Postgres health before starting ;; Demo data seeds on an empty database"
"US-24|Check whether Vigil itself is healthy|epic:ops,must-have,devops,backend|2|As an operator, I want a health endpoint reporting its own dependencies so that Docker and my proxy can make routing decisions.|GET /health reports api, database, and cache individually ;; It returns 200 with status degraded when a dependency is down ;; The container HEALTHCHECK uses it"
"US-25|Ship changes without breaking main|epic:ops,should-have,devops,ci|5|As a maintainer, I want CI to run tests and build images on every PR so that main stays deployable.|Every PR runs pytest, next build, and docker build for both services ;; A failing job blocks the merge ;; Merging to main publishes tagged images"
)
